# Setting the format of the prompt
# format = """
# $username\
# $directory\
# $all\
# $character"""

format = """
  $character \
$all
"""

# Catppuccin color pallete
palette = "catppuccin_mocha"

right_format = """$cmd_duration"""

# Inserts a blank line between shell prompts
add_newline = true

# Making a single line prompt
[line_break]
disabled = true

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[âœ—](bold red)"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

# Adding Battery status to the prompt
[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "

[[battery.display]] # "bold red" style and discharging_symbol when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]] # "bold yellow" style and ğŸ’¦ symbol when capacity is between 10% and 30%
threshold = 20
style = "yellow"
discharging_symbol = "ï– "

# Setting time on the prompt
[time]
disabled = true
format = 'ï€— [\[ $time \]]($style) '
time_format = "%T"
utc_time_offset = "+5.5"
time_range = "00:00:00-24:00:00"
use_12hr = false
style = "bold green"

[cmd_duration]
min_time = 500
format = "took [$duration](bold yellow)"

[hostname]
ssh_only = false
# format = "[$ssh_symbol](bold blue) on [$hostname](bold red) "
format = "[$hostname](bold red) "
# trim_at = ".companyname.com"
disabled = true

[username]
style_user = "bold green"
format = "[$user]($style)"
disabled = true
show_always = true

[aws]
symbol = "îŒ½  "
format = "[$symbol($version) ]($style)"

[conda]
symbol = "ï„Œ "
format = "[$symbol($version) ]($style)"

[dart]
symbol = "î˜ "
format = "[$symbol($version) ]($style)"

[c]
symbol = "î˜ "
format = "[$symbol($version) ]($style)"

[directory]
home_symbol = "~"
style = "bold blue"

[docker_context]
symbol = "ïŒˆ "
format = "[$symbol($version) ]($style)"

[elixir]
symbol = "î‰µ "
format = "[$symbol($version) ]($style)"

[elm]
symbol = "î˜¬ "
format = "[$symbol($version) ]($style)"

[git_branch]
symbol = "ï˜ "
format = "[$symbol$branch]($style) "
style = "bold italic red"

[git_status]
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "î˜§ "
format = "[$symbol($version) ]($style)"

[haskell]
symbol = "î· "
format = "[$symbol($version) ]($style)"

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "
format = "[$symbol($version) ]($style)"

[julia]
symbol = "î˜¤ "
format = "[$symbol($version) ]($style)"

[memory_usage]
symbol = "ó°› "
format = "[$symbol($version) ]($style)"

[nix_shell]
symbol = "ï‹œ "
format = "[$symbol($version) ]($style)"

[nodejs]
symbol = "îœ˜ "
format = "[$symbol($version) ]($style)"

[perl]
symbol = "î© "
format = "[$symbol($version) ]($style)"

[php]
symbol = "î˜ˆ "
format = "[$symbol($version) ]($style)"

[python]
symbol = "î˜† "
format = "[$symbol($version) ]($style)"

[ruby]
symbol = "îˆ¾ "
format = "[$symbol($version) ]($style)"

[rust]
symbol = "î¨ "
format = "[$symbol($version) ]($style)"

[scala]
symbol = "îœ· "
format = "[$symbol($version) ]($style)"

[shlvl]
symbol = "ï„  "
format = "[$symbol($version) ]($style)"

[swift]
symbol = "î• "
format = "[$symbol($version) ]($style)"

[lua]
symbol = "î˜  "
format = "[$symbol($version) ]($style)"

[bun]
disabled = true
